workspace = { members = [ "capi/opencc-fmmseg-capi","tools/opencc-clip", "tools/opencc-rs"] }
[package]
name = "opencc-fmmseg"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.11.0"
serde_json = "1.0.132"
serde = { version = "1.0.210", features = ["derive"] }
rayon = "1.10.0"
lazy_static = "1.5.0"