workspace = { members = [ "capi/opencc-fmmseg-capi","tools/opencc-clip", "tools/opencc-rs"] }
[package]
name = "opencc-fmmseg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.4"
serde_json = "1.0.115"
serde = { version = "1.0.197", features = ["derive"] }
rayon = "1.10.0"
